### ISSUE TITLE
Check if line exists before parsing in parsestandardfiles

### ISSUE THREAD

**Issue by kdheepak** [NREL/PowerSystems.jl#101]

**Comment by jd-lara** [comment]
@kdheepak can we close this one?

**Comment by kdheepak** [comment]
I think what I meant was that we would end up with an unexpected error if the bus referenced in the line did not exist. This is already addressed in #94 over [here](https://github.com/NREL/PowerSystems.jl/blob/9d914d485a269cc4b6a7fe6de83f424f8a137fcf/src/parsers/pm_io/data.jl#L815). To close this issue, take a file such as [this one](https://github.com/NREL/PowerSystemsTestData/blob/a2519eb503d06b451ac0a55b8663abf581b9f81a/matpower/case5.m#) and ensure that if we remove this [line](https://github.com/NREL/PowerSystemsTestData/blob/a2519eb503d06b451ac0a55b8663abf581b9f81a/matpower/case5.m#L25) it throws a sane error when it finishes parsing the file and runs the checks / validation on the system. If that happens we can close this issue.

**Comment by daniel-thom** [comment]
We do get an error, but I don't think it is the best possible behavior.  Refer to the output below.  Errors are logged, but the code continues until it hits a runtime KeyError exception.  I think that fatal errors should halt execution as soon as they are detected.  There are 18 instances of error log prints in src/parsers/pm_io/data.jl.  I could convert them all to throw(DataFormatError(msg)).  What you do you think @kdheepak?

parse_matpower: ┌ Error: bus 10 in generator 5 is not defined
└ @ PowerSystems /mnt/c/Users/dthom/Sandboxes/daniel-thom-PowerSystems.jl/src/parsers/pm_io/data.jl:804
┌ Error: to bus 10 in branch 7 is not defined
└ @ PowerSystems /mnt/c/Users/dthom/Sandboxes/daniel-thom-PowerSystems.jl/src/parsers/pm_io/data.jl:820
┌ Error: to bus 10 in branch 3 is not defined
└ @ PowerSystems /mnt/c/Users/dthom/Sandboxes/daniel-thom-PowerSystems.jl/src/parsers/pm_io/data.jl:820
Parse Matpower data files: Error During Test at /mnt/c/Users/dthom/Sandboxes/daniel-thom-PowerSystems.jl/test/parse_matpower.jl:17
  Got exception outside of a @test
  KeyError: key "10" not found
  Stacktrace:
   [1] getindex(::Dict{String,Array{Any,1}}, ::String) at ./dict.jl:478
   [2] check_bus_types(::Dict{String,Any}) at /mnt/c/Users/dthom/Sandboxes/daniel-thom-PowerSystems.jl/src/parsers/pm_io/data.jl:967

**Comment by daniel-thom** [comment]
Closing per changes in pull request #175
