### ISSUE TITLE
Check consistency of the data when making a PowerSystem

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#109]
We have mixed units in the PowerSystem. There has to be consistency when creating a system and make sure all the data is in P.U.

**Comment by jd-lara** [comment]
- [ ] Check the relationship of baseMVA w.rt. MW in data for limits
- [ ] Check the relationship of baseMVA w.rt. MW in data for peak load.
- [ ] Check the values of the provided angles w.r.t 3.14

**Comment by claytonpbarrows** [comment]
I agree. However, this is similar to #98 and #99 where I did the opposite implementation and made the parser conform to the mixed-units.
This should also help address numerical scaling issues when we encounter them.

**Comment by jd-lara** [comment]
@claytonpbarrows I am reviewing all the code that makes the checks as per the check-list above such that we always know the data is in p.u. and in radians when building a PowerSystem.

**Comment by jd-lara** [comment]
It seems that there is no good way to find out if the data is in P.U. or in MW. The only device where this is possible is the branches. We need to figure out a way to guarantee that the data in a PowerSystem is all in PU. Otherwise we will run into problems in PowerSimulations.

**Comment by claytonpbarrows** [comment]
Lets start with a short document describing the calculations of P.U. for each type of device. Short of extensive data checking and validation, flexible implementation (user defines if data is in P.U.) and good documentation is probably the best substitute.

**Comment by ccoffrin** [comment]
If you want to be serious about units, you might also consider using a package like https://github.com/ajkeller34/Unitful.jl/ to be very explicit about it in the implementation layer.
