### ISSUE TITLE
Develop a function to update information

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#112]

**Comment by claytonpbarrows** [comment]
Currently the design is that a `PowerSystem` struct contains the timeseries information for relevant devices. This creates an issue in PowerSimulations.jl where creating problems on time selections that are not perfectly aligned with the timeseries included in the `PowerSystem` requires the re-instantiation of the `PowerSystem` object. 
I believe that the correct resolution is to:
 1. Depend only on the timeseries information in the `Forecast` structs when creating/simulating problems in PowerSystems.jl
 2. Remove the population of timeseries fields such as `scalingfactor` in the `PowerSystem` struct and the related device structs.
 3. Provide the appropriate checks to ensure that the required timeseries information exists in a `Forecast` struct to enable a PowerSimulation with a `PowerSystem` struct.

I'll leave this open for comment, then migrate to new issues from 1, 2, and 3 as the discussion dictates.

**Comment by jd-lara** [comment]
I am for option 2 and then have more time series structs where we would have a device field that we can use to point to the device for which this is relevant.

**Comment by claytonpbarrows** [comment]
@jd-lara is that to say that you are in support of the proposal that includes all of 1, 2, & 3? Because I think that 2 isn't strictly necessary, but would be a good idea to improve clarity.

**Comment by jd-lara** [comment]
@claytonpbarrows yes, implement 1 but not only for forecasts also a new struct for just time series. 
Implement 2 to simplify how the data looks like and also is parsed and 3 might be needed or not.

**Comment by claytonpbarrows** [comment]
@jd-lara, in some sense everything that we have enabled in PowerSimulations is optimizing schedules against a 'forecast', so until we do something different, I don't see the need for a new struct.

**Comment by jd-lara** [comment]
This will be resolved with the implementation of the time-series update in PowerSimulations.

**Comment by jd-lara** [comment]
I am closing this since now all the structs are mutable.
