### ISSUE TITLE
Add no-load generation costs

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSystems.jl#115]
- [ ] add field to `EconThermal` struct
 - [ ] enable population from MATPOWER files

**Comment by claytonpbarrows** [comment]
OK. While I like that terminology (I think it makes a lot more sense than the "no-load" terminology), it's easily confused with fixed (regardless of on/off status) costs... which was the source of @kdheepak and my confusion... should we change the name, or leave as is?  either way the cost definition will require some good documentation

**Comment by jd-lara** [comment]
The name is ok to change. The main question is why this matters in the ED problem? This will just dd a constant to the objective function. This cost component is only relevant to the UC problem.
