### ISSUE TITLE
add warnings when changing values

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSystems.jl#120]
e.g. when running calculatelinelimits...

**Comment by jd-lara** [comment]
@claytonpbarrows is this still valid or can we close it?

**Comment by claytonpbarrows** [comment]
I think it's still valid. I definitely cannot confirm that it should be closed.

**Comment by daniel-thom** [comment]
@claytonpbarrows We generate warnings in checkanglelimits and calculatethermallimits.  Do you know of any specific place where we don't?

**Comment by claytonpbarrows** [comment]
I just looked through system_checks.jl It looks like everything is covered. Closing
