### ISSUE TITLE
Improve the container for many devices. 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#121]
Currently, we store PowerSystem devices in Arrays when creating a `PowerSystem`, this is efficient from the Memory POV. However, this forces us to access the data by using a list comprehension over the array or by having to index explicitly `ArrayName[ix]`. This implementation defeats the purpose of what PowerSystems does by improving the access and use of Power System data. This is evident when taking a deeper look at how things are done in PowerSimulations to manipulate the data from PowerSystems. 

We need to test several container options that we can index with a better format in order to avoid this practice. I am thinking of `AxisArrays`, `AbstractArrays` or eventually `Dicts` but we need to make performances tests for this.

**Comment by ccoffrin** [comment]
Can you give an example of one of these list comprehension operations?  I presume it is used to build a list of a specific field of a component?

PS: `Dict` FTW!

**Comment by jd-lara** [comment]
for instance this to get the name sets 

`gen_names = [g.name for g in ArrayofGens if g.available]`

**Comment by ccoffrin** [comment]
Can you give a little more context on why this is slow?  Other than allocating arrays over and over it's not clear to me how it can be made faster.

If array allocation is the time sink, then something like this could work around it,
```
for g in ArrayofGens
   if g.available
       <various computations related to g>
   end
end
```

**Comment by jd-lara** [comment]
The problem is when combined with JuMP and we want to access data then it leads to this kind of code or even more complicated versions. 

```Julia 
for (ix, devices) in enumerate(ArrayofDevices)
     @contraint(m, Var[ArrayofDevices[ix].name] >= ArrayofDevices[ix].data)
end
```

**Comment by ccoffrin** [comment]
What about something like this,
```
for device in ArrayofDevices
   if device.available
      @constraint(m, Var[device.name] >= device.data)
   end
end
```
I think that would be pretty fast.

**Comment by jd-lara** [comment]
That will work for many of the cases, I will implement that as I refactor to anonymous variables soon. Thanks @ccoffrin

**Comment by jd-lara** [comment]
@ccoffrin I am leaning towards using dicts similar to PowerModels but store the device using PowerSystems types. This will also make easier the integration and DataWrangling.

**Comment by jd-lara** [comment]
@ccoffrin Exactly. Still researching if using strings for indexing is the best alternative. I made some tests with AxesArrays, the features are cool but the speed is not great, and it complicates interoperability with other languages.

**Comment by claytonpbarrows** [comment]
Starting a thread on this topic [here](https://gitter.im/NREL/PowerSystems.jl)

**Comment by daniel-thom** [comment]
Issue is resolved by the above pull request.
