### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#125]
~~Add regression tests for parsing @kdheepak #107~~ 
~~`parsestandardfiles()` with a time series folder specification~~
- [x] `cdm_parser` @claytonpbarrows 
~~- [ ] `json2ps_parser.jl` @claytonpbarrows  can you confirm this is still necessary? ~~
- [x] @errors in `pm2ps_parser.jl`
- [x] `pm_io` @kdheepak can you take a look a this folder missing tests?  #102 
- [x] `ybus_calculations.jl` @jd-lara #80 #79 
- [x] `print.jl` @jjstickel

**Comment by jd-lara** [comment]
@daniel-thom We had this issue opened about the parsing testing that is relevant to today's conversation. Many of the missing tests are relevant to the parsing.

**Comment by daniel-thom** [comment]
@jd-lara Regarding the @error messages in pm2ps_parser.jl, is your point that we should have negative tests that trip these errors?  Secondly, if they are fatal errors then I propose we throw an exception instead of just logging it.  Do you agree?

**Comment by jd-lara** [comment]
@claytonpbarrows and @daniel-thom what's the status of this issue?
