### ISSUE TITLE
Shell commands to git in build.jl don't work on Windows

### ISSUE THREAD

**Issue by kdayday** [NREL/PowerSystems.jl#129]
Haven't figured out a direct solution yet.

**Comment by jd-lara** [comment]
@kdayday can you provide more detail? All out build tests are passing in the CI, so it is likely your local git.

**Comment by kdheepak** [comment]
@kdayday can you tell us which git commands?

**Comment by kdayday** [comment]
Yep, sorry, here's more info. It appears that using "run()" or accessing the shell through ";" doesn't work on Windows the way you'd expect for something called a "shell", discussed here:
https://github.com/JuliaLang/julia/pull/23703
Not only do git commands not work, but other basic commands don't either, e.g. "echo hello" gets an error:
"ERROR: IOError: could not spawn `echo hello`: no such file or directory (ENOENT)"
I get the same "no such file or directory" error for the "git clone" call in build.jl, as well as with "dir", etc.

Two leads:
1) It looks like the proper way of dealing with calls like "echo" in Julia's shell on Windows is "cmd /c echo hello", and this works for me.  However, "cmd /c git init" gives me a new error: "'git' is not recognized as an internal or external command, operable program or batch file". So maybe at that point, it is a local git problem, or there is a different call besides "cmd" that I haven't found. 
2) It looks like the expected shell calls work if you run Julia from Git Bash: 
https://discourse.julialang.org/t/usable-shell-on-windows-yay/5988
That seems wrong to assume users are working from Git Bash, and won't solve the problem for me in Jupyter Notebooks. I didn't go further to verify if I could get things working from Git Bash.

The general point being, these "run()" calls may be breakable across platforms, at least that's what it looks like for a newbie like me. In this specific case, maybe the question is whether and how to include the test data.

**Comment by kdheepak** [comment]
Thanks for the detailed information. The build.jl just downloads a data git repository, if you don't need to run tests or examples you can comment it out and bypass it for now. We'll add a more portable fix soon.

**Comment by kdheepak** [comment]
I think this will not be an issue if git bash, powershell or windows
subsystem for linux is used. But that will be a small percent of people.
I'll add a fix for Windows CMD.

**Comment by jd-lara** [comment]
I will close, this issue since it is not related to PowerSystems. This is an issue of the user set-up in Windows. cc. @kdayday @kdheepak
