### ISSUE TITLE
clean the usage of "nothing" and "missing"

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSystems.jl#158]

**Comment by jd-lara** [comment]
@claytonpbarrows What do you mean?

**Comment by daniel-thom** [comment]
@claytonpbarrows I think this issue can be closed. The codebase uses nothing instead of missing, and based on my understanding from our discussions, that is by design.  Do you agree?

**Comment by claytonpbarrows** [comment]
agreed
