### ISSUE TITLE
Abstract Type Containers 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#159]
This issue is related to #121. When we store in an Array the devices of a certain type, normally we end up with a container that has AbstractType. This is not advisable as noted [here](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-containers-with-abstract-type-parameters-1). 

This also created a classification problem in PowerSimulations.jl when we need to discriminate elements of the Array by type. For instance, taking out a Fixed Resource RenewableEnergy generator from the dispatchable ones. 

Would it be better to re-think how we store the collection of devices in a way that we end up only with Arrays that contain `structs`

**Comment by claytonpbarrows** [comment]
@jd-lara can you explain why this is "Urgent"

**Comment by jd-lara** [comment]
There is a significant penalty on performance when containers contain abstract types. For instance `Array{Generators,1}` is pretty bad compared to `Array{ThermalGen,1}`

**Comment by claytonpbarrows** [comment]
Started a thread related to this topic [here](https://gitter.im/NREL/PowerSystems.jl)

**Comment by daniel-thom** [comment]
Issue is resolved by pull request #190
