### ISSUE TITLE
Illegal instruction error when reading EVI-Pro files using MAT package

### ISSUE THREAD

**Issue by bwbush** [NREL/PowerSystems.jl#161]
Report from @ugirumurera :

> I have created code to populate the BevDemand struct. It can successful populate one struct, but having trouble using it to populate an array of BevDemand structs (getting “signal (4): Illegal instruction: 4”).. I am also attaching a zip folder containing short code and sample “.mat” file to review the I/O function.
[IO_code.zip](https://github.com/NREL/PowerSystems.jl/files/2941761/IO_code.zip)

**Comment by kdheepak** [comment]
Sounds like a seg fault? Can we have a stacktrace?

**Comment by bwbush** [comment]
@ugirumurera : 

The memory management in the [MAT package](https://github.com/JuliaIO/MAT.jl) sometimes conflicts with memory management in Julia 1.0.3.  Putting the data from `readmat` directly into the `BevDemand` struct results in the illegal instruction error when that data is later accessed.

I tried copying and deep copying, but that didn't work, so I resorted to the following workaround that converts the data to a string and then parses it, ensuring the deepest, most independent copy possible.  This workaround is undesirable because it slows down the reading.

https://github.com/NREL/PowerSystems.jl/blob/f507ef165fbcf9c63828cba2117f5e19729e0d8c/src/models/demand/bev_demand.jl#L240-L259

We may want to submit a minimal example of this problem to the maintainers of MAT.

**Comment by bwbush** [comment]
@kdheepak The stack trace was not informative because the fault occurs long after memory was corrupted.

If you look at the code I posted, simply setting [`workaround1 = false`](https://github.com/NREL/PowerSystems.jl/blob/f507ef165fbcf9c63828cba2117f5e19729e0d8c/src/models/demand/bev_demand.jl#L240) causes the memory corruption.

**Comment by bwbush** [comment]
Here is example code from @ugirumurera, with my workarounds, and example data: 
* https://dl.bwbush.io/Test_populate.jl
* https://dl.bwbush.io/FlexibleDemand.mat

**Comment by bwbush** [comment]
@ugirumurera Please test the workarounds and close this issue if they are satisfactory.

**Comment by ugirumurera** [comment]
The workarounds worked. We can look at using another data format for cleaner code in future.
