### ISSUE TITLE
Differentiate AC and DC (fast) maximum charging rates

### ISSUE THREAD

**Issue by bwbush** [NREL/PowerSystems.jl#162]
@ewood57 writes

> Yes, I think separate vehicle attributes for max acceptable AC and DC power is appropriate. Most PHEVs on the market today aren’t DC capable and would have an effective DC max power of zero. It’s also my understanding that the on-board charger in most (if not all) BEVs is only rated up to 20kW while most can accept DC charge rates of up to 50kW (more in some cases).

**Comment by bwbush** [comment]
@ugirumurera In 8b87b50d426c3cf833e7c0bfae8b767556775a1c I made split the `chargeratemax` into `chargerateacmax` and `chargeratedcmax` and added a DC entry to `locations` in `BevDemand`.  This is a minimalist approach to differentiating AC and DC charging.

Another approach would be to create a `ChargeRates` struct along the following lines and then use that for both `chargeratemax` and `locations`.
```julia
struct ChargeRates
    acrate :: Float64
    dcrate :: Float64
end
```
so `BevDemand` would become
```julia
struct BevDemand{T,L} <: FlexibleDemand{T,L}
    locations           :: MobileDemand{T,Tuple{L,ChargeRates}}
    consumptions        :: TemporalDemand{T}
    batterymin          :: Float64
    batterymax          :: Float64
    timeboundary        :: Union{Tuple{Float64,Float64},Nothing}
    chargeratemax       :: ChargeRates
    dischargeratemax    :: Float64
    chargeefficiency    :: Float64 # FIXME: Technically, this is a joint property of the EVSE and the BEV.
    dischargeefficiency :: Float64
end
```
This approach is a little more complex (since it adds a struct), but also more self-explanatory.  I slightly prefer this.

What do you think?

**Comment by ugirumurera** [comment]
Makes sense. We work from this.

**Comment by bwbush** [comment]
@ugirumurera Just to clarify, do you prefer the proposed change in [the comment above](https://github.com/NREL/PowerSystems.jl/issues/162#issuecomment-472417880) or the change in commit 8b87b50d426c3cf833e7c0bfae8b767556775a1c?

**Comment by jd-lara** [comment]
I recommend looking into the data structure for storage 
https://github.com/NREL/PowerSystems.jl/blob/master/src/models/storage/batteries.jl

We use NamedTuples for max and mins to reduce the field size and also for charging and discharging efficiencies.

**Comment by bwbush** [comment]
@jd-lara Named tuples look like a great way to handle this.  We'll proceed accordingly.  Thanks.

**Comment by ugirumurera** [comment]
@bwbush I had not read your comment correctly. I like the second approach too. Code that is self explanatory is easier to maintain. the NamedTuples looked self-explanatory too. So either one would be fine with me.

**Comment by bwbush** [comment]
@ugirumurera I just committed 592891e63f2a76927ac36cef263daee4c106ca95, which uses the named-tuple approach that @jd-lara suggested:
https://github.com/NREL/PowerSystems.jl/blob/592891e63f2a76927ac36cef263daee4c106ca95/src/models/demand/bev_demand.jl#L43-L50

Would you please revise `populate_BEV_demand` accordingly?

**Comment by ugirumurera** [comment]
@bwbush Got it, will work from this.

**Comment by ugirumurera** [comment]
@bwbush just committed changes with revised populate_BEV_demand on demand-response branch. I think we are now ready to produce a scenario of EVs. Do we know how many EVs we want to start with? I can process EVI-Pro data accordingly.

**Comment by bwbush** [comment]
@ugirumurera I created `/projects/siip/demand-response/` on Eagle for us to store the BEV datafiles.  We can start with 1000 BEVs for testing purposes.  I will test the files.

Would you please look at the https://github.com/Gridmod/rts-gmlc system and calculate by how much the generation capacity exceeds the load?  Eventually we'll want to run scenarios with enough BEVs to consume all of that excess capacity.

@sourabhdalvi Do you know if https://github.com/Gridmod/rts-gmlc runs in the recently refactored https://github.com/NREL/PowerSystems.jl and https://github.com/NREL/PowerSimulations.jl ?

**Comment by bwbush** [comment]
@ugirumurera Let's use https://github.nrel.gov/SIIP/dr-study-1 for discussions and files specific to the demand-response case study.

**Comment by ugirumurera** [comment]
@bwbush Got it, added folder for EVI-Pro data with 1000 EVs data set at https://github.nrel.gov/SIIP/dr-study-1/tree/master/EVI-Pro_Data

**Comment by jd-lara** [comment]
@bwbush can you update the status of this? it is stale

**Comment by bwbush** [comment]
stale
