### ISSUE TITLE
LaPack error in buildlodf()

### ISSUE THREAD

**Issue by DillonJ** [NREL/PowerSystems.jl#165]
Hi folks,

Greetings from the Spine project! 

https://github.com/Spine-project
www.spine-model.org/spine_toolbox.htm

I've successfully calculated ptdfs for my network using `PowerSystems.buildptdf()`

However, I'm getting Lapack errors in `buildlodf()` at `LODF = gemm('N','N',H,getri!(Dem,dipiv))`. I have a suspicion it's for outages that result in islanding and/or orphaned tails.

Any suggestions?

**Comment by jd-lara** [comment]
Yes, the matrix operations used in LOLDF will fail if the incidence matrix has islands or results in too many radial circuits. Certainly we can make the calculation more robust by checking for those before sending the matrices to to the `buildlodf()` function. 

If you have the data at hand to test that would be great.

**Comment by claytonpbarrows** [comment]
I think this is being caused by the existence of radial connections.  For example, I can recreate the issue with the following code:
```
nodes3    = [Bus(1,"nodeA", "PV", 0, 1.0, (min = 0.9, max=1.05), 230),
             Bus(3,"nodeB", "PQ", 0, 1.0, (min = 0.9, max=1.05), 230),
             Bus(2,"nodeC", "SF", 0, 1.0, (min = 0.9, max=1.05), 130),

        ];

branches3 = [Line(name = "1", available = true, 
                connectionpoints = (from=nodes5[1],to=nodes5[2]), 
                r=0.00281, x=0.0281, b=(from=0.00356, to=0.00356)),
             Line(name = "3", available = true, 
                connectionpoints = (from=nodes5[1],to=nodes5[3]), 
                r = 0.00064, x = 0.0064, b = (from=0.01563, to=0.01563)),
];
PowerSystems.buildlodf(branches3,nodes3)
```
But when I add another line connecting buses 3 and 4, the `buildlodf()` executes fine.

Perhaps [this document](http://www.ee.umn.edu/class/ee8725/HW%204%20ANSWER%20KEY.pdf) contains a resolution...

**Comment by DillonJ** [comment]
So I guess you just want to skip outages where PTDF(n,m,k) = 1 and warn the user.

**Comment by jd-lara** [comment]
@claytonpbarrows the suggested document is a good idea. We have the PTDF review branch, we can implement that there.

**Comment by sourabhdalvi** [comment]
Radial lines in the LODF matrix from now will have 0's and a  -1, little different from MATPower where they use NaN's and -Inf
