### ISSUE TITLE
Create method to allow users to pass configuration options into PowerSystem construction.

### ISSUE THREAD

**Issue by daniel-thom** [NREL/PowerSystems.jl#174]
Currently, users can pass specific customizations with kwargs to the PowerSystem constructor.  This can be improved.

**Comment by jd-lara** [comment]
@daniel-thom is this part of the discussion here https://github.com/NREL/PowerSystems.jl/pull/206#discussion_r276319238

**Comment by daniel-thom** [comment]
Yes.  Things have evolved quite a bit since I created this issue.

**Comment by jd-lara** [comment]
I will add it to v0.4.0

**Comment by jd-lara** [comment]
@daniel-thom what's the status of this? Did it got fixed with the new concrete system?

**Comment by daniel-thom** [comment]
No, still open.  I'll do this in my next set of changes.

**Comment by jd-lara** [comment]
@daniel-thom can we close this now?

**Comment by daniel-thom** [comment]
Yes, I think this is covered now.
