### ISSUE TITLE
EconThermal values can't be serialized to JSON

### ISSUE THREAD

**Issue by daniel-thom** [NREL/PowerSystems.jl#198]
The struct defines variablecost as Union{Function,Array{Tuple{Float64, Float64}}}.  A value with a Function cannot be serialized.  It needs to be converted before being serialized.

**Comment by jd-lara** [comment]
I am not sure how to approach this since one of the things we want to have is precisely the capability (that no one else has) of using arbitrary cost functions. This is even more relevant when we consider load damage curves and things like that.

**Comment by daniel-thom** [comment]
Dheepak and Clayton had some ideas.  At a minimum we could store the data that we use to create the function in make_thermal_gen().

**Comment by jd-lara** [comment]
Given that we currently only support Linear and Quadratic Objective functions then we can somewhat limit the scope of this field. But we will need to come up with other ideas later on for arbitrary functions.
