### ISSUE TITLE
ConcreteSystem with parametric subtypes

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSystems.jl#201]
The [ConcreteSystem](https://github.com/NREL/PowerSystems.jl/blob/dev/src/base.jl#L169) breaks when the system includes parametric subtypes like [`Deterministic`](https://github.com/NREL/PowerSystems.jl/blob/dev/src/models/forecasts.jl#L8)

@daniel-thom, @jd-lara, @kdheepak I'm not sure how to proceed.

**Comment by kdheepak** [comment]
Can you explain what error you are getting? Or can you provide the test case where it is breaking?

**Comment by daniel-thom** [comment]
I think that this can be solved with a bit of special handling for Forecasts.  It seems like we should treat them completely differently from Devices.  But I want to understand the recursion issue Dheepak mentioned in his PR.  Let's discuss the right fix tomorrow morning.

**Comment by claytonpbarrows** [comment]
- move `GenClasses`, `TechnicalParams`, and `Forecasts` out from `Component` and into `PowerSystemType`
 - Change `Forecasts.device` to `Forecasts.component`

**Comment by jd-lara** [comment]
This is part of the task to redefine the type-tree according to what was discussed last week.

**Comment by daniel-thom** [comment]
Fixed by commit d8f8c22959147f8a98cd37f00f352ffb7ef65bce.
