### ISSUE TITLE
Add support for UUIDs in all PowerSystems structs.

### ISSUE THREAD

**Issue by daniel-thom** [NREL/PowerSystems.jl#203]
In order to be able to allow users to delete components or forecasts from a PowerSystem each object will need to store a UUID.

When an object is first created it should call UUIDs.uuid4(). This UUID should be stored in the object as an internal attribute.  The user should be able to remove an object with something like:

delete!(system, forecast)

Our code can then retrieve the UUID and delete it from the underlying data structure.

We have three proposals to solve this:
1. Add a UUID field to every struct.
2. Create a new PowerSystemInternal struct that contains a UUID.  If we ever add new fields in the future, it will be much easier.
3. Implement a macro that automatically adds fields to a struct.

We should defer this work until after the JSON serialization work (PR #199) is complete.

**Comment by daniel-thom** [comment]
Here is another reason to implement UUIDs:  better support serialization of a PowerSystem.

PowerSystems sometimes stores references to components in other data structures.  For example, ProportionalReserve has contributingdevices::Array{Device} that gets populated with references to actual devices.  When we serialize ProportionalReserve to JSON the information will be duplicated in the JSON string.  If a user were to change values in the main instance of the device but not in the secondary places then deserialization will not produce an identical System.

Solution:  Serialize out the UUIDs for these secondary references.

This would solve another problem.  Deserialization of abstract types is difficult with the current JSON libraries because there is no standard way of encoding the type of each object.

**Comment by jd-lara** [comment]
We would then need to implement some of these changes with inner constructors in the device types such that the users can't create devices with custom UUIDs. In the proposal number 2, what do you mean with add new fields in the future?

**Comment by daniel-thom** [comment]
In order to support deserialization we have to support a constructor that accepts a UUID (or PowerSystemInternal).

Adding this struct to every existing struct is very tedious work.  If we ever need to add a field in the future then we could add it to this one struct - one change in one file.

**Comment by jd-lara** [comment]
Do we want this to be resolved for v0.4.0?

**Comment by daniel-thom** [comment]
I'm working on it right now.  It's needed for (1) allowing removal of components and (2) JSON serialization.  It should not block 0.4.0, but can go in if it's ready.

**Comment by jd-lara** [comment]
@daniel-thom thanks, if it is ready on time then we can add it.

**Comment by daniel-thom** [comment]
Fixed by PR #209
