### ISSUE TITLE
Rename ThermalDispatch

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#226]
We need to rename the type PSY.ThermalDispatch struct since both PowerSimulations and PowerSystems export the same name. 

@claytonpbarrows any ideas?

**Comment by jd-lara** [comment]
same for `RenewableCurtailment`

**Comment by claytonpbarrows** [comment]
what about `RenewableCurtailment` and `ThermalDispatch` in `PSI`, and `RenewableCurtailable` and `ThermalDispatchable` in `PSY`

**Comment by daniel-thom** [comment]
This is only a problem if someone performs "using PowerSystems" from within PowerSimulations.  No one should be doing that, right?  If the current names are actually the best then this should be fine.  People would need to always type PSY.ThermalDispatch.

**Comment by jd-lara** [comment]
The use of the packages is together and I wouldn't expect users to be doing the prefixes as we do.

**Comment by jd-lara** [comment]
I made a proposal for name change in #247
