### ISSUE TITLE
Forecast field in ConcreteSystem should be indexed with integers

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#227]
When the forecasts are generated and parsed into System or Concrete System the keys in the dictionary are `:DA` or `:RTS`, defined from a 

```const SystemForecasts = Dict{Symbol, Forecasts}``` 

However, this would generate a System with forecasts that use two different time-scales. I propose we use 

```const SystemForecasts = Dict{Int64, Forecasts}```

Where every entry in the SystemForecasts Dict corresponds to a consistent collection of forecasting time series with the same `resolution` and `initialtime` fields that later can be lopped over. 

Moreover, there no reason to make `:DA` the default type of forecast.

**Comment by daniel-thom** [comment]
This will be fixed by PR #233.  However, the solution will be different that what is described here.  Forecast will be stored in the System like this:

const Forecasts = Vector{<:Forecast}
const IssueTime = NamedTuple{(:resolution, :initialtime),
                             Tuple{Dates.Period, Dates.DateTime}}
const SystemForecasts = Dict{IssueTime, Forecasts}

**Comment by jd-lara** [comment]
fixed via #233
