### ISSUE TITLE
Fix printing

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#23]

**Comment by jdlara-berkeley** [comment]
The printing functions need refactoring to accommodate the new PowerSystem struct

**Comment by claytonpbarrows** [comment]
@jjstickel if #117 addresses this, feel free to cloes

**Comment by jjstickel** [comment]
I think its @jd-lara 's call. If he is sufficiently satisfied with my initial rudimentary catch-all, then he can close it. I plan to write specific print functions for some of the types.

**Comment by jd-lara** [comment]
@jjstickel in your next PR you can close this issue after adding tests.

**Comment by jjstickel** [comment]
Will do. I started working on tests yesterday.

**Comment by jjstickel** [comment]
Completed with https://github.com/NREL/PowerSystems.jl/commit/07cc7ec108227f6ecf89b5d6d41d15a34fdff0cb
