### ISSUE TITLE
get_components Array return option 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#230]
We should have a version of `get_components` that returns a vector of components. There is value in having an iterator but here is also some applications where an Array will be useful.

**Comment by daniel-thom** [comment]
This is trivial to implement but do we really need it?  The user could just as easily call collect on the result of get_components.  Here's how it plays out practically:
1. components = collect(get_components(RenewableFix, sys))
2. components = get_components_as_vector(RenewableFix, sys))
3. components = get_components(RenewableFix, sys, Vector)

I prefer the first.

**Comment by jd-lara** [comment]
I am asking for this as many of our users won't have too much Julia experience to directly use the iterators. This is mostly to facilitate looking at the data in an array when needed. it is not an urgent thing but I think will make it more user-friendly.

**Comment by daniel-thom** [comment]
Will an example in the docstring solve the problem?

**Comment by daniel-thom** [comment]
Here is the current docstring. Please consider that this is a simpler solution than adding another public function.

help?> get_components
get_components(
                 ::Type{T},
                 sys::System,
                )::FlattenedVectorsIterator{T} where {T <: Component}

  Returns an iterator of components. T can be concrete or abstract. Call collect on the result if an array is desired.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  iter = PowerSystems.get_components(ThermalDispatch, sys)
  iter = PowerSystems.get_components(Generator, sys)
  generators = PowerSystems.get_components(Generator, sys) |> collect
  generators = collect(PowerSystems.get_components(Generator, sys))

**Comment by jd-lara** [comment]
LGTM as an alternative
