### ISSUE TITLE
Parsing code needs to support the new forecast format

### ISSUE THREAD

**Issue by daniel-thom** [NREL/PowerSystems.jl#234]
Pull request #233 introduces a new data layout for forecasts.  The parsing code and System constructors that take a ps_dict as a parameter rely on the old layout and need to be updated.

**Comment by jd-lara** [comment]
We should fix this issue in #233 before merging.

**Comment by daniel-thom** [comment]
I agree that that is ideal.  However, it involves a lot more changes.  When do you want it #233 merged?

**Comment by jd-lara** [comment]
We need both issues addressed since I have to parse the CDM data to make tests in PowerSimulations.  I will review the code today and we can merge soon.

**Comment by daniel-thom** [comment]
Not necessarily.  There is a workaround.
system = System(PowerSystems._System(old_constructor_inputs))

**Comment by jd-lara** [comment]
ok, then I will review it and we can merge

**Comment by daniel-thom** [comment]
Actually, this is such a big mess now that I will try to fix the parsing code today.

**Comment by daniel-thom** [comment]
Nope.  I take it back.  :(
