### ISSUE TITLE
get_XXX functions API spec

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#235]
In the recent implementation of `get_forecasts`, `get_components` there is an inconsistency in the returns types. Any current or future implementation of a `get_XXX` function needs to return a concrete type or a container with concrete types. 

- Given the components of the system
- When I attempt to when I try to get a container with the devices of interest for modeling,
- Then the return needs to be specified by a concrete PowerSystem type or be of a concrete type. For instance `Array{ConcreteType}`.

**Comment by daniel-thom** [comment]
Should the get_forecasts functions accept a Type parameter, similar to get_components?

**Comment by jd-lara** [comment]
yes, that would make it more clear.

**Comment by daniel-thom** [comment]
Fixed by PR #248
