### ISSUE TITLE
add a get_forecast_length method

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#236]
besides the `get_forecast_issue_times` we also need a function to get the length of the forecasts.

**Comment by daniel-thom** [comment]
This should already work for both get_forecasts functions.  One returns an iterator that supports length() and the other returns a vector.

```
julia> issue_time
NamedTuple{(:resolution, :initialtime),Tuple{Dates.Period,Dates.DateTime}}((5 minutes, 2020-01-01T00:00:00))

julia> iter = get_forecasts(s, issue_time);

julia> length(iter)
134
```

**Comment by jd-lara** [comment]
see #237 for what I mean.
