### ISSUE TITLE
make SystemForecasts a struct 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#238]
Currently, we have all the system forecasts stored in a dict defined as `const SystemForecasts = Dict{IssueTime, Forecasts}`. I will be more useful to have a struct that contains metadata about the forecasts that are needed to build Simulations from a group of forecasts. 

For instance 

```Julia
struct SystemForecasts
    data::Dict{IssueTime, Forecasts}
    inital_time::Date.DateTime
    resolution::Dates.Period
    horizon::Int64
    interval::Dates.Period
end
```

for this struct we would make the methods `get_` for each of the fields.

**Comment by claytonpbarrows** [comment]
similar to [this comment](https://github.com/NREL/PowerSystems.jl/pull/233#pullrequestreview-236359595)

**Comment by daniel-thom** [comment]
This is contradictory in a couple of ways.
1. You said you wanted to store forecasts by concrete type, similar to components. Do you still want that?  If so, there needs to be Dict{DataType, ConcreteForecastType}.  Perhaps nested under issue_time dicts?
2. Each forecast has initial_time and resolution fields (IssueTime).  SystemForecasts currently includes all forecasts, i.e., multiple IssueTimes.  So, you struct above doesn't really make sense. Does this mean you want multiple SystemForecasts instances in a System such that all forecasts within an instance would have the same IssueTime?

**Comment by jd-lara** [comment]
You are correct about 1. That is still a requirement, using a tuple `(IssueTime, ConcreteType)` seems like a good approach to do this. 

About 2, each System will contain one `SystemForecasts` struct. We want to have multiple issue times in the keys and they are separated by an amount `interval`. Also, we would have repeated information about the `resolution` but this will allow the flexibility of using the forecasts types independently from a group of them. I think it is a small overhead that increases use cases of different types.

**Comment by daniel-thom** [comment]
@jd-lara Can you specify where the SystemForecasts values for initial_time, resolution, horizon, and interval should come from?  I think you said that initial_time should be the earliest initial_time of any forecast, but I'd like to see it written here.

Secondarily, the existing Forecast structs define the field "initialtime" instead of "initial_time" that you wrote here.  I think these field names should be consistent.  Please specify your preference.  Globally changing to initial_time is trivial, but would probably impact your PowerSimulations code.

**Comment by jd-lara** [comment]
1. let's use initial_time. The original versions of this code are older than some of the guidelines we adopted over the last months.

2. Initial_time is the earliest forecast in the system. 

3. Resolution is the resolution field in the forecasts stored inside the SystemForecasts structs. I acknowledge that it will imply a repetition of data. However, this will preserve the option of using a forecast type by itself for smaller simulations instead of having to always create a SystemForecasts struct. 

4. The horizon is the length of the forecasts inside of the SystemStruct and should be consistent for all and needs to be inferred or specified by the user. 

5. Interval needs to be inferred by the Period between forecast issue times or specified by the user. 

For instance, the RTS data has two sets of time series data (we would only use one of them for the system creation) with these characteristics by default when parsed into the dict. 

- 1-hour resolution data, lookahead of 24 steps (for 24 hours) and 1-hour interval. 
- 5-minute resolution data, lookahead of 12 steps (for 60 minutes/5 minutes) and 5-minute interval. 

However, depending on the simulation I need, I might want something like one of these

- 1-hour resolution data, lookahead of 48 steps (for 48 hours) and 1-hour interval. 
- 5-minute resolution data, lookahead of 12 steps (for 60 minutes/5 minutes) and 1-hour interval.
