### ISSUE TITLE
method overwrite 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#239]
We have these warnings showing up after merging #233. 

```
WARNING: Method definition read(IO, Type{Dates.DateTime}) in module JSON2 at /Users/jdlara/.julia/packages/JSON2/J5VUB/src/read.jl:210 overwritten in module PowerSystems at /Users/jdlara/.julia/packages/PowerSystems/sZYeA/src/models/serialization.jl:74.
WARNING: Method definition read(IO, Type{Dates.DateTime}) in module JSON2 at /Users/jdlara/.julia/packages/JSON2/J5VUB/src/read.jl:210 overwritten in module PowerSystems at /Users/jdlara/.julia/packages/PowerSystems/sZYeA/src/models/serialization.jl:74.
```

**Comment by daniel-thom** [comment]
Sorry, I should have made a case and notified you guys.  Here is the comment I put in the code for this:

```Julia
"""Enables JSON deserialization of Dates.DateTime.
The default implementation in JSON2's read.jl fails to convert the string to DateTime
because of a bug - using ISODateFormat instead of ISODateTimeFormat.
JSON2 is fixed but hasn't released a version yet.
"""
JSON2.read(io::IO, ::Type{Dates.DateTime},
           format=Dates.ISODateTimeFormat) = Dates.DateTime(JSON2.read(io, String), format)
```

**Comment by jd-lara** [comment]
This brings up again the concerns of using Packages that might not have long term support.

**Comment by daniel-thom** [comment]
Ok, then let's switch to a language where the standard library already supports a rich set of features.  ;)

The developers of this package fixed this bug two weeks ago.  As of now it is actively supported.  This is a non-critical feature, so we could disable it if we ever needed to.  If we want this functionality, I think this is the best available resource.

**Comment by jd-lara** [comment]
I updated the version of JSON2 in the project and the manifest so it shouldn't be a problem anymore.

**Comment by daniel-thom** [comment]
Ok, looks like they just bumped it.  We need to delete my overloaded function in serialization.jl to make the warning go away.
