### ISSUE TITLE
Parsing of forecast data upgrades

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#249]
The current implementation of parsing forecast data in `cdm_parser.jl` has the forecasts names hardcoded and generates the keys for the `ps_dict` based on the name of the files. As a result, a `ps_dict` can contain more than one set of time series and more than one resolution, yet the name of the time series doesn't reflect the distinction between sets of time series. 

This creates a challenge when creating SystemForecasts since a System should contain forecasts of the same resolution. Also, this parsing scheme for the forecasts won't allow the user to specify a look-ahead and an interval to slice the time series data according to their specifications. 

The proposal to tackle these shortcomings is as follows: 

1.  Assuming the time series data is provided as columns as currently stored in the CDM data format, when parsing the forecast data, eliminate the use ok hardcoded keys "DA" and "RT" and substitute that with a tuple of the resolution of the data and the length of the time series. Hence, we will have ~DA~ => (1 Hour, 8760) and ~RT~ => (5 Minutes, 105120). 

2. With this information, we store in `ps_dict` a configuration for the forecast arrays that specify the time series to be used, interval and length of the lookahead. Probably this will require some interface functions to avoid direct manipulation of the `ps_dict`. 

3. The `make_forecat_array` function takes the selected time series data set and the specification (interval, lookahead) and generates the `SystemForecast` struct accordingly. This function will throw exceptions/warnings or errors if there are inconsistencies in the data lengths or time_steps. 

Simple functions like `missing_data = setdiff(whole_year,dates_of_parsed_data)` can show if there are inconsistencies across the time series data or missing data points.

**Comment by daniel-thom** [comment]
This comment is a suggestion for a general change in how we store the forecast data while parsing.  We currently build a deeply nested dictionary like this:

```
dict["forecasts"]["DA"]["gen"]["Renewable"]["PV"] = {
    name => TimeSeries.TimeArray(),
}
```

This introduces a few problems with the code:
- complexity
- hard to extend
    * What happens if you want to add something in between "gen" and "Renewable?"
    * Other people will have difficulty matching this format with their data.

Instead, we could store arrays of dictionaries with known fields like the example below.  This would make it easier to build our System and Forecast structs, easier to extend for other people's data, etc.

```
dict["forecasts"] = [
    {
        "name" => "324_PV_3",
         "label" => "DA",
        "generator" => "Renewable",
        "type" => "PV",
        "resolution" => Dates.Minute(5),
        "length" => 8760,
        "data" => TimeSeries.TimeArray(),
    },
]
```
