### ISSUE TITLE
Add check for proper data version when running unit tests.

### ISSUE THREAD

**Issue by daniel-thom** [NREL/PowerSystems.jl#280]
The unit test code should make sure it has the expected version of test data before running any tests.  It currently only checks for the existence of a data directory.  If a developer has an outdated version then they might waste a bunch of time debugging failures.

A solution could be something like this:
- Anytime an interface change is made to the data version, that developer could create a new version or tag.  This should include the branch.  A file checked into the data repo should contain the tag and/or version.
- The PowerSystems repo should include the data version in a string or file.  The developer who changes the data version must also change this version.
- When the PowerSystems unit tests start, the code should check that the existing data version is correct.  Upon mismatch it should throw an error.  It should not overwrite the data, as that directory could be a symlink to a data repo.

**Comment by jd-lara** [comment]
we can implement this solution "he PowerSystems repo should include the data version in a string or file. The developer who changes the data version must also change this version." by making releases in the data repo.

**Comment by claytonpbarrows** [comment]
current thinking is to resolve most of these problems by porting the data.jl files to another supported format. This would resolve most of these problems, and not require a fancy data version tracker.

**Comment by jd-lara** [comment]
I think this is still relevant since we don't only make changes to the data.jl files. There are instances where the CDM data has changed.
