### ISSUE TITLE
Order of Ybus indexes incorrect

### ISSUE THREAD

**Issue by scdhulipala** [NREL/PowerSystems.jl#292]
When I use YB = Ybus(c_sys14) with the 14-Bus System file, the order of Ybus is not 1....14 but indexed  in the following order:

Dimension 1, [6, 9, 12, 11, 7, 4, 13, 2, 14, 8, 10, 3, 1, 5]
 Dimension 2, [6, 9, 12, 11, 7, 4, 13, 2, 14, 8, 10, 3, 1, 5]

This can get confusing to the users.

**Comment by claytonpbarrows** [comment]
this can be accomplished by giving the `Ybus` function a sorted set of buses. 

```
Ybus(get_components(Branch, c_sys14), sort!(get_components(PSY.Bus, c_sys14), v -> PSY.get_number(v)))
```

I'm not convinced that we need to support this functionality natively. If we do, I think it should be a kwarg option in the `Ybus` function.

**Comment by claytonpbarrows** [comment]
closing in favor of #293
