### ISSUE TITLE
Sort the order of buses when using _get_components

### ISSUE THREAD

**Issue by scdhulipala** [NREL/PowerSystems.jl#293]
When you use **_get_components(Bus, c_sys14)_** in PowerSystems, this is the output we get,

PowerSystems.FlattenIteratorWrapper{Bus}(Bus,Base.Iterators.Flatten{Array{Base.ValueIterator,1}}(Base.ValueIterator[Bus[Bus(name="Bus 6"), Bus(name="Bus 9"), Bus(name="Bus 12"), Bus(name="Bus 11"), Bus(name="Bus 7"), Bus(name="Bus 4"), Bus(name="Bus 13"), Bus(name="Bus 2"), Bus(name="Bus 14"), Bus(name="Bus 8"), Bus(name="Bus 10"), Bus(name="Bus 3"), Bus(name="Bus 1"), Bus(name="Bus 5")]]), 14)

The order of buses should be sorted to be displayed from 1 to 14.

**Comment by daniel-thom** [comment]
This is by design.  The buses are stored in a dictionary, so they are unordered.  If you want them ordered then you can do something like this:

buses = get_components(Bus, c_sys14)
sorted_buses = sort!(collect(buses), by=x->x.number)

**Comment by jd-lara** [comment]
We want a sort function that can do this on a collection of buses.

**Comment by daniel-thom** [comment]
The design goal was to keep this code as efficient as possible.  Sorting requires new memory allocation and processing.

**Comment by jd-lara** [comment]
That's ok, we only need this for building network matrices.

**Comment by daniel-thom** [comment]
Can we remove the URGENT + Bug labels?  There is a very simple workaround. This can be an enhancement request.  It also raises a question of whether we want sorting capabilities per component type.  We could do something elegant to handle all cases.

**Comment by daniel-thom** [comment]
I would suggest a function along the lines of get_sorted_components(T, sys)

**Comment by jd-lara** [comment]
It's a bug in the network matrix construction, it should come in a particular order.

**Comment by jd-lara** [comment]
> I would suggest a function along the lines of get_sorted_components(T, sys)

Not all components have a numerical field to sort them by. This is relevant mostly for the buses.
