### ISSUE TITLE
Should Arc have a circuit field?

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSystems.jl#304]
... for parallel lines?

**Comment by jd-lara** [comment]
Parallel lines should be made out of n-parallel lines even if the share the same arc.

**Comment by claytonpbarrows** [comment]
with a field to identify the circuit, or just a recognition that they are distinct objects/uuid's?

**Comment by jd-lara** [comment]
Parallel lines can have the same arc `uuid` and be independent objects. Alternatively, they can be collected into a circuit struct.

**Comment by jd-lara** [comment]
Decided not, parallel lines are implicitly defined by having the same arc.
