### ISSUE TITLE
Procedural algorithm for greedy BEV charging fails some tests.

### ISSUE THREAD

**Issue by bwbush** [NREL/PowerSystems.jl#306]
[`greedydemands`](https://github.com/bwbush/PowerSystems.jl/blob/2679ba405a15afb5f13d16f57c0d1e4dac7038fc/src/models/demand/bev_demand.jl#L328-L512) fails 11/1000 test cases for charging plans.

**Comment by jd-lara** [comment]
@bwbush what is the status of this issue? Can we close it as stale?

**Comment by bwbush** [comment]
stale
