### ISSUE TITLE
Type of data retrieved from Network Matrices is not known during run time

### ISSUE THREAD

**Issue by kdheepak** [NREL/PowerSystems.jl#310]
The type of data retrieved from the Ybus is not known by the compiler. If this data is used in following code it results in poor type inference. 

<img width="845" alt="Screen Shot 2019-08-27 at 2 51 28 AM" src="https://user-images.githubusercontent.com/1813121/63756624-e9c15080-c875-11e9-91a1-82b636c238d4.png">

Related to implementation here:

https://github.com/NREL/PowerSystems.jl/blob/83ee65216c2df3eabc4a3e7c98e67a07029cd236/src/utils/network_calculations/ybus_calculations.jl#L1-L14

**Comment by jd-lara** [comment]
The problem seems to be in the overloaded `Base.getindex` function that is not able to infer the eltype in the matrix being passed.

**Comment by jd-lara** [comment]
This is also the case for other network matrices 
```Julia
@code_typed P5["1", 1]
CodeInfo(
1 ─ %1  = (getfield)(idx, 1)::String
│   %2  = (getfield)(idx, 2)::Int64
│   %3  = invoke PowerSystems.to_index(_2::PTDF, %1::String, %2::Int64)::Tuple{Any,Any}
│   %4  = Base.getfield(A, :data)::Array{Float64,2}
│   %5  = (getfield)(%3, 1)::Any
│   %6  = (getfield)(%3, 2)::Any
│   %7  = (isa)(%5, Int64)::Bool
│   %8  = (isa)(%6, Int64)::Bool
│   %9  = (and_int)(%7, %8)::Bool
└──       goto #3 if not %9
2 ─ %11 = π (%5, Int64)
│   %12 = π (%6, Int64)
│   %13 = Base.arrayref(true, %4, %11, %12)::Float64
└──       goto #4
3 ─ %15 = Base.getindex(%4, %5, %6)::Any
└──       goto #4
4 ┄ %17 = φ (#2 => %13, #3 => %15)::Any
└──       return %17
) => Any
```
