### ISSUE TITLE
Update notebooks with proper examples 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#32]
Remove development notebooks and add essential examples.

**Comment by jdlara-berkeley** [comment]
@claytonpbarrows I removed the Notebooks folder to add it as a download as well with data. I will add the folder to the integrated modeling repo to develop the examples properly there.

**Comment by kdheepak** [comment]
Why remove notebooks? You can view notebooks from GitHub so it's useful to have it in there.

**Comment by jdlara-berkeley** [comment]
@kdheepak Isn't better to have the examples displayed in the documentation? In this way, the repo contains only the Julia code.

**Comment by kdheepak** [comment]
Agreed. If we show it in the docs, I don't see a strong need to add the notebooks to the repo.

**Comment by jd-lara** [comment]
Create examples of: 

- [ ] Read and explore data 
- [ ] Make a Economic Dispatch Case 
- [ ] Solve a PowerFlow with NLopt.

**Comment by claytonpbarrows** [comment]
moved this to another repository
