### ISSUE TITLE
Fix print statements 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#325]
Make show statements return Summary by default to improve display in REPL and Notebooks.

**Comment by claytonpbarrows** [comment]
@jjstickel can you help with this since you did it for a previous version?
Basically, we want `print(sys)` to show the output that you get when you run:
```
print(summary(sys))
```

**Comment by jjstickel** [comment]
Sure. Is it urgent? I can probably take a look on Thursday.

**Comment by daniel-thom** [comment]
Don't we won't to override show instead?

```julia
Base.show(io::IO, sys::System) = print(io, summary(sys))
@show sys
```

**Comment by jd-lara** [comment]
Correct, I made the requirement more clear.
