### ISSUE TITLE
Define future of 3W transformer 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#37]

**Comment by claytonpbarrows** [comment]
For now, we should rely on pre-translation of 3w transformers to the transformer-line single phase equivalent model (see p.77 of [Electric Energy Systems 2nd ed](https://www.crcpress.com/Electric-Energy-Systems-Second-Edition-Analysis-and-Operation/Gomez-Exposito-Conejo-Canizares/p/book/9781138724792) )
