### ISSUE TITLE
Units of PowerSystems.

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#43]
Should PowerSystems be stored in p.u. or in MW? For now, we have a mix, but we should be consistent and avoid issues in modeling. This is related to #10 and in particular, complicates the modeling of line flows.

**Comment by claytonpbarrows** [comment]
The [standardfiles_parser.jl](https://github.com/NREL/PowerSystems.jl/blob/master/src/parsers/standardfiles_parser.jl#L12) calls `make_mixed_units()` on the `pm_dict`

**Comment by jd-lara** [comment]
We have already determined that all the values in a System Struct are in p.u.
