### ISSUE TITLE
Implement PTDF and other Array operations with StaticArrays 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#48]
Modify the allocation in 

https://github.com/NREL/PowerSystems.jl/blob/5ad4dbe1c5e7da79c2f4e82b8519ae761e05dd97/src/utils/ptdf_calculations.jl#L3

To use  https://github.com/JuliaArrays/StaticArrays.jl

This might help with the memory issues for large systems.

**Comment by sourabhdalvi** [comment]
Static Arrays don't support BLAS/LAPACK .
BLAS/LAPACK is much faster, we don't need Static Arrays.
