### ISSUE TITLE
Time step consistency between ramping rates and time series

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#50]

**Comment by claytonpbarrows** [comment]
@jd-lara  now that I'm digging into this, I'm not sure why we're doing it. Specifically, what are we trying to accomplish? Basically, I'm having trouble understanding what to do if, for example, a generator can ramp it's entire nameplate capacity in less than the shortest time step in the dataset. Should we just make warnings? I don't think it's appropriate to throw errors or restrict behavior in PowerSimulations...

**Comment by jd-lara** [comment]
we should make warnings but the check is if the time-step in the time-series data i.e., 1-hour, 5-minutes. etc is consistent with the ramp-rate limits and the time-values. For instance, a generator with a ramp limit of 1 MW/hr is equivalent to 0.0833 MW/5-min. We need to make sure the delta units of time are consistent with the data when constructing a Power System. 

@sourabhdalvi made a very similar check with the line limits and it is executed when constructing the powersystem.
