### ISSUE TITLE
Improve parsing

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#76]
Remove transform between String and Substring. Implement `CSV.jl` or `CSVFile.jl` only for parsing data `.csv`

**Comment by claytonpbarrows** [comment]
`CSV.jl` appears to be faster. Thus, I only replaced it's usage with `CSVFile.jl` where `CSV.jl` was failing.

**Comment by jd-lara** [comment]
@claytonpbarrows I am still surprised it breaks only for some files, I am wondering why

**Comment by claytonpbarrows** [comment]
![image](https://user-images.githubusercontent.com/7231396/47213706-06891f80-d359-11e8-9fa2-1423b54b3b38.png)

**Comment by claytonpbarrows** [comment]
since CSV hangs, I'll use Pandas.

**Comment by claytonpbarrows** [comment]
Things seem to be better now, I'm closing this
