### ISSUE TITLE
Move parsing info/warnings to a Log file 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#78]
We should move the printouts of the warnings/info from the parsing into a log file and remove the printouts on the screen.

**Comment by jd-lara** [comment]
@claytonpbarrows can you look at this while fixing the parsing? We have too many printouts while parsing and it is not really informative to the user.

**Comment by claytonpbarrows** [comment]
@kdheepak did you resolve this?

**Comment by jd-lara** [comment]
@kdheepak can we close this now?

**Comment by daniel-thom** [comment]
Implemented by pull request #171
