### ISSUE TITLE
Document units in devices structs

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSystems.jl#82]
things like ramp limits have units. We need a clear documentation of what they are, and some QC around the parsing to ensure that appropriate unit conversions are made.

**Comment by jd-lara** [comment]
We need to make sure that when a `PowerSystem.jl` the user is aware that all the units are assumed in p.u. otherwise, it will be a nightmare to generalize `PowerSimulations.jl`

**Comment by jjstickel** [comment]
I presume p.u. means "power unit", but what is that? Also, where are you thinking documentation is needed?

**Comment by claytonpbarrows** [comment]
p.u. means "per unit".

**Comment by jd-lara** [comment]
I will close this since its a duplicate from #65
